version: '3.8'

services:
  manager:
    networks:
      - my-network
    image: nginx:1.17
#    environment:
#      - ENV_DOCKER_HOST_AUTH=host.internal:8081 # OrbStack
#      - ENV_DOCKER_HOST_CORE=host.internal:8082 # OrbStack
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/app/html
    ports:
      - "8888:80"
networks:
  my-network:
    driver: bridge
